baseURL: http://localhost:1313/
defaultContentLanguage: zh
languageCode: zh-cn
title: Guide

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: github-dark
    lineNos: false
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

params:
  showPrivate: false
