baseURL: http://localhost:1313/
defaultContentLanguage: zh
languageCode: zh-cn
title: Guide

markup:
  goldmark:
    renderer:
      unsafe: true
    renderHooks:
      image:
        # 使用 layouts/_markup/render-image.html，不要走内置 hook
        useEmbedded: never
  highlight:
    noClasses: false
    style: github-dark
    lineNos: false
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

params:
  showPrivate: false
